Repository cerner/carbon-graphs, pull requests merged in 2019-10, with the labels that each got.

#89 Fix: To not trigger popup for not truncated trackLabel (fixes #20)
  src/main/js/controls/Gantt/Track.js
  src/test/unit/controls/Gantt/Track-spec.js
Labels: bug

#67 New: Panning property added
  CONTRIBUTORS.md
  dev/app.js
  dev/app.less
  dev/examples/controls/bar.js
  dev/examples/controls/gantt.js
  dev/examples/controls/line.js
  dev/examples/controls/pairedResult.js
  dev/examples/controls/panHelpers.js
  dev/examples/controls/timeline.js
  docs/controls/Gantt.md
  docs/controls/Panning.md
  docs/controls/Timeline.md
  docs/core/GraphAPI.md
  src/main/js/controls/Bar/Bar.js
  src/main/js/controls/Bar/helpers/goalLineHelpers.js
  src/main/js/controls/Bar/helpers/selectionHelpers.js
  src/main/js/controls/Bar/helpers/translateHelpers.js
  src/main/js/controls/Gantt/Gantt.js
  src/main/js/controls/Gantt/GanttConfig.js
  src/main/js/controls/Gantt/helpers/activityHelpers.js
  src/main/js/controls/Gantt/helpers/creationHelpers.js
  src/main/js/controls/Gantt/helpers/datapointHelpers.js
  src/main/js/controls/Gantt/helpers/taskHelpers.js
  src/main/js/controls/Gantt/helpers/translateHelpers.js
  src/main/js/controls/Graph/Graph.js
  src/main/js/controls/Graph/GraphConfig.js
  src/main/js/controls/Graph/helpers/helpers.js
  src/main/js/controls/Line/Line.js
  src/main/js/controls/Line/helpers/helpers.js
  src/main/js/controls/PairedResult/PairedResult.js
  src/main/js/controls/PairedResult/helpers/helpers.js
  src/main/js/controls/PairedResult/helpers/selectionIndicatorHelpers.js
  src/main/js/controls/Pie/PieConfig.js
  src/main/js/controls/Pie/helpers/translateHelpers.js
  src/main/js/controls/Timeline/Timeline.js
  src/main/js/controls/Timeline/TimelineConfig.js
  src/main/js/controls/Timeline/helpers/creationHelpers.js
  src/main/js/controls/Timeline/helpers/translateHelpers.js
  src/main/js/core/BaseConfig/helper.js
  src/main/js/helpers/axis.js
  src/main/js/helpers/constants.js
  src/main/js/helpers/dateline.js
  src/main/js/helpers/datetimeBuckets.js
  src/main/js/helpers/label.js
  src/main/js/helpers/region.js
  src/main/js/helpers/utils.js
  src/test/unit/controls/Bar/Bar-spec.js
  src/test/unit/controls/Gantt/Gantt-spec.js
  src/test/unit/controls/Graph/Graph-spec.js
  src/test/unit/controls/Graph/helpers.js
  src/test/unit/controls/Line/Line-spec.js
  src/test/unit/controls/PairedResult/PairedResult-spec.js
  src/test/unit/controls/Timeline/Timeline-spec.js
Labels: enhancement

#94 Chore: Gantt Events Icon
  dev/examples/controls/gantt.js
  package-lock.json
Labels: chore

#91 Chore: Split unit tests into more atomic files (fixes #36)
  build/karma/karma.config.js
  package-lock.json
  src/test/unit/controls/Bar/AxisInfoRow-Spec.js
  src/test/unit/controls/Bar/Bar-spec.js
  src/test/unit/controls/Bar/BarLoad-spec.js
  src/test/unit/controls/Bar/BarPanning-spec.js
  src/test/unit/controls/Bar/BarRegions-spec.js
  src/test/unit/controls/Bar/BarUnload-spec.js
  src/test/unit/controls/Bar/GroupedBar-spec.js
  src/test/unit/controls/Bar/StackedBar-spec.js
  src/test/unit/controls/Gantt/Action-spec.js
  src/test/unit/controls/Gantt/Activity-spec.js
  src/test/unit/controls/Gantt/Event-spec.js
  src/test/unit/controls/Gantt/Gantt-spec.js
  src/test/unit/controls/Gantt/GanttGenerate-spec.js
  src/test/unit/controls/Gantt/GanttLoad-spec.js
  src/test/unit/controls/Gantt/GanttPanning-spec.js
  src/test/unit/controls/Gantt/GanttResize-spec.js
  src/test/unit/controls/Gantt/GanttUnload-spec.js
  src/test/unit/controls/Gantt/Task-spec.js
  src/test/unit/controls/Gantt/Track-spec.js
  src/test/unit/controls/Graph/CombinationGraph-spec.js
  src/test/unit/controls/Graph/Graph-spec.js
  src/test/unit/controls/Graph/GraphAxes-spec.js
  src/test/unit/controls/Graph/GraphDateline-spec.js
  src/test/unit/controls/Graph/GraphGenerate-spec.js
  src/test/unit/controls/Graph/GraphNoData-spec.js
  src/test/unit/controls/Graph/GraphPanning-spec.js
  src/test/unit/controls/Graph/GraphResize-spec.js
  src/test/unit/controls/Graph/GraphUnload-spec.js
  src/test/unit/controls/Graph/helpers.js
  src/test/unit/controls/Line/Line-spec.js
  src/test/unit/controls/Line/LineCriticality-spec.js
  src/test/unit/controls/Line/LineLoad-spec.js
  src/test/unit/controls/Line/LinePanning-spec.js
  src/test/unit/controls/Line/LineRegion-spec.js
  src/test/unit/controls/Line/LineUnload-spec.js
  src/test/unit/controls/PairedResult/PairedResult-spec.js
  src/test/unit/controls/PairedResult/PairedResultCriticality-spec.js
  src/test/unit/controls/PairedResult/PairedResultLoad-spec.js
  src/test/unit/controls/PairedResult/PairedResultPanning-spec.js
  src/test/unit/controls/PairedResult/PairedResultRegion-spec.js
  src/test/unit/controls/PairedResult/PairedResultUnload-spec.js
  src/test/unit/controls/Pie/Pie-spec.js
  src/test/unit/controls/Pie/PieLoad-spec.js
  src/test/unit/controls/Pie/PieUnload-spec.js
  src/test/unit/controls/Timeline/Timeline-spec.js
  src/test/unit/controls/Timeline/TimelineCriticality-spec.js
  src/test/unit/controls/Timeline/TimelineLoad-spec.js
  src/test/unit/controls/Timeline/TimelinePanning-spec.js
  src/test/unit/controls/Timeline/TimelineResize-spec.js
  src/test/unit/controls/Timeline/TimelineUnload-spec.js
  src/test/unit/core/Shape/Shape-spec.js
  src/test/unit/helpers/commonHelpers.js
Labels: chore

#96 Chore: Updated eslint rules to eslint-plugin-standard
  .eslintrc.json
  .stylelintrc
  README.md
  dev/app.js
  dev/examples/controls/bar.js
  dev/examples/controls/gantt.js
  dev/examples/controls/pairedResult.js
  dev/examples/controls/panHelpers.js
  dev/examples/data.js
  dev/examples/helpers.js
  package-lock.json
  package.json
  src/main/js/controls/Bar/helpers/axisInfoRowHelpers.js
  src/main/js/controls/Bar/helpers/creationHelpers.js
  src/main/js/controls/Bar/helpers/goalLineHelpers.js
  src/main/js/controls/Gantt/helpers/activityHelpers.js
  src/main/js/controls/PairedResult/PairedResult.js
  src/main/js/controls/Pie/PieContent.js
  src/main/js/core/BaseConfig/BaseConfig.js
  src/main/js/core/Construct/Construct.js
  src/main/js/core/GraphContent/GraphContent.js
  src/main/js/helpers/region.js
  src/main/js/locale/index.js
  src/main/less/controls/Line.less
  src/main/less/controls/Timeline.less
  src/main/less/core.less
  src/test/unit/controls/Bar/GroupedBar-spec.js
  src/test/unit/controls/Bar/StackedBar-spec.js
  src/test/unit/controls/Carbon/helpers.js
  src/test/unit/controls/Gantt/Task-spec.js
Labels: chore

#98 Fix: prevents onclick trigger for non truncated axis row label (fixes #90)
  CONTRIBUTORS.md
  src/main/js/controls/Bar/helpers/axisInfoRowHelpers.js
  src/test/unit/controls/Bar/AxisInfoRow-Spec.js
Labels: bug

#97 Provide space for padding property when hasCustomPadding is true.
  src/main/js/helpers/axis.js
  src/test/unit/controls/Graph/GraphGenerate-spec.js
  src/test/unit/controls/Graph/GraphResize-spec.js
  src/test/unit/controls/Graph/GraphUnload-spec.js
Labels: bug

#103 Update: Add border for legend item (fixes #28)
  README.md
  build/index.html
  dev/app.less
  dev/examples/controls/bar.js
  dev/examples/controls/gantt.js
  dev/examples/controls/line.js
  dev/examples/controls/pairedResult.js
  dev/examples/controls/timeline.js
  dev/examples/panHelpers.js
  docs/contributing/README.md
  docs/core/Graph.md
  package-lock.json
  package.json
  src/main/less/core.less
  src/test/unit/controls/Bar/BarPanning-spec.js
  src/test/unit/controls/Gantt/GanttPanning-spec.js
  src/test/unit/controls/Graph/GraphPanning-spec.js
  src/test/unit/controls/Line/LinePanning-spec.js
  src/test/unit/controls/PairedResult/PairedResultPanning-spec.js
Labels: documentation, enhancement
