Repository cerner/carbon-graphs, pull requests merged in 2019-09, with the labels that each got.

#68 New: No Data View (fixes #39)
  CONTRIBUTORS.md
  dev/app.js
  dev/examples/controls/line.js
  dev/examples/data.js
  docs/README.md
  docs/core/GraphAPI.md
  package.json
  src/main/js/controls/Gantt/GanttConfig.js
  src/main/js/controls/Gantt/helpers/creationHelpers.js
  src/main/js/controls/Graph/Graph.js
  src/main/js/controls/Graph/GraphConfig.js
  src/main/js/controls/Graph/helpers/helpers.js
  src/main/js/controls/Timeline/TimelineConfig.js
  src/main/js/controls/Timeline/helpers/creationHelpers.js
  src/main/js/helpers/axis.js
  src/main/js/helpers/constants.js
  src/main/js/helpers/styles.js
  src/main/js/locale/de-DE.js
  src/main/js/locale/en-AU.js
  src/main/js/locale/en-CA.js
  src/main/js/locale/en-GB.js
  src/main/js/locale/en-US.js
  src/main/js/locale/es-ES.js
  src/main/js/locale/fr-FR.js
  src/main/js/locale/ja-JP.js
  src/main/js/locale/pt-BR.js
  src/main/less/colors.less
  src/main/less/core.less
  src/test/unit/controls/Graph/Graph-spec.js
Labels: enhancement

#73 Chore: Added custom padding tab for site (fixes #69)
  dev/app.js
  dev/examples/controls/line.js
  dev/examples/controls/timeline.js
  package-lock.json
  package.json
  src/main/js/controls/PairedResult/helpers/helpers.js
  src/main/less/core.less
Labels: chore

#76 Chore: Update concept goal-line vs region-line (fixes #38)
  dev/app.js
  dev/examples/controls/line.js
  docs/controls/Bar.md
  package-lock.json
  package.json
  src/main/js/controls/Bar/helpers/goalLineHelpers.js
  src/main/js/controls/PairedResult/helpers/helpers.js
  src/main/js/helpers/constants.js
  src/main/js/helpers/region.js
  src/test/unit/controls/Bar/Bar-spec.js
  src/test/unit/controls/Line/Line-spec.js
  src/test/unit/controls/PairedResult/PairedResult-spec.js
Labels: chore

#82 Chore: Update devdependencies and removed codeowners
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  build/webpack/helpers/rules.js
  package-lock.json
  package.json
  src/main/js/controls/Timeline/helpers/creationHelpers.js
  src/test/unit/controls/Timeline/Timeline-spec.js
Labels: chore

#85 Docs: Restructured examples, added getting started page
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/README.md
  docs/assets/carbon-getting-started.png
  docs/controls/Bar.md
  docs/controls/Gantt.md
  docs/controls/Line.md
  docs/controls/PairedResult.md
  docs/controls/Pie.md
  docs/controls/Timeline.md
  docs/core/GraphAPI.md
  docs/getting-started/GettingStarted.md
  docs/helpers/Dateline.md
Labels: documentation

#87 Update: Added support provide key for unload Graph contents (fixes #86)
  README.md
  docs/README.md
  docs/assets/construct-interface.png
  docs/controls/Bar.md
  docs/controls/Line.md
  docs/controls/PairedResult.md
  docs/core/GraphAPI.md
  docs/core/Interface.md
  docs/core/Lifecycle.md
  package-lock.json
  package.json
  src/main/js/controls/Bar/Bar.js
  src/main/js/controls/Bar/helpers/resizeHelpers.js
  src/main/js/controls/Graph/Graph.js
  src/main/js/helpers/legend.js
  src/main/less/core.less
  src/test/unit/controls/Bar/Bar-spec.js
  src/test/unit/controls/Gantt/Gantt-spec.js
  src/test/unit/controls/Graph/Graph-spec.js
  src/test/unit/controls/Line/Line-spec.js
  src/test/unit/controls/PairedResult/PairedResult-spec.js
  src/test/unit/controls/Timeline/Timeline-spec.js
Labels: enhancement
