Repository cerner/carbon-graphs, pull requests merged in 2019-07, with the labels that each got.

#10 New: Criticality for Timeline Points
  CONTRIBUTORS.md
  dev/app.js
  dev/examples/controls/criticality.js
  docs/controls/Timeline.md
  src/main/js/controls/Timeline/TimelineContent.js
  src/main/js/controls/Timeline/helpers/creationHelpers.js
  src/main/js/core/Shape/shapeDefinitions.js
  src/main/js/helpers/constants.js
  src/main/js/helpers/styles.js
  src/main/less/controls/Timeline.less
  src/main/less/core.less
  src/test/unit/controls/Timeline/Timeline-spec.js
  src/test/unit/controls/Timeline/helpers.js
Labels: enhancement

#46 Build: Added karma-parallel to run tests in parallel (fixes #44)
  build/karma/karma.config.js
  package-lock.json
  package.json
Labels: build

#42 New: Native Pie chart
  README.md
  dev/app.js
  dev/examples/controls/line.js
  dev/examples/controls/pie.js
  dev/examples/data.js
  dev/examples/helpers.js
  dev/examples/popup.js
  docs/README.md
  docs/controls/Bar.md
  docs/controls/Gantt.md
  docs/controls/Line.md
  docs/controls/PairedResult.md
  docs/controls/Pie.md
  docs/controls/Timeline.md
  docs/core/GraphAPI.md
  docs/helpers/Dateline.md
  package-lock.json
  package.json
  src/main/js/controls/Pie/Pie.js
  src/main/js/controls/Pie/PieConfig.js
  src/main/js/controls/Pie/PieContent.js
  src/main/js/controls/Pie/helpers/creationHelpers.js
  src/main/js/controls/Pie/helpers/translateHelpers.js
  src/main/js/controls/index.js
  src/main/js/helpers/constants.js
  src/main/js/helpers/errors.js
  src/main/js/helpers/legend.js
  src/main/js/helpers/loadUtil.js
  src/main/js/helpers/styles.js
  src/main/less/carbon.less
  src/main/less/controls/Pie.less
  src/main/less/core.less
  src/test/unit/controls/Carbon/Carbon-spec.js
  src/test/unit/controls/Carbon/helpers.js
  src/test/unit/controls/Gantt/Gantt-spec.js
  src/test/unit/controls/Graph/Graph-spec.js
  src/test/unit/controls/Pie/Pie-spec.js
  src/test/unit/controls/Pie/helpers.js
  src/test/unit/controls/Timeline/Timeline-spec.js
Labels: enhancement

#55 Update: Load and unload batch of tracks (fixes #51)
  docs/controls/Gantt.md
  src/main/js/controls/Gantt/Gantt.js
  src/main/js/controls/Pie/Pie.js
  src/main/js/helpers/constructUtils.js
  src/main/js/helpers/loadUtil.js
  src/test/unit/controls/Gantt/Gantt-spec.js
Labels: enhancement

#48 Update: Disabled legend item appearance is now distinct (fixes #47)
  package-lock.json
  package.json
  src/main/js/helpers/legend.js
  src/main/less/core.less
  src/test/unit/controls/Line/Line-spec.js
Labels: enhancement

#59 Fix: Regions not rendering combination with Paired Result (fixes #40)
  dev/examples/controls/combination.js
  package-lock.json
  package.json
  src/main/js/controls/Bar/helpers/goalLineHelpers.js
  src/main/js/helpers/region.js
  src/test/unit/controls/Gantt/Gantt-spec.js
  src/test/unit/controls/Graph/CombinationGraph-spec.js
Labels: bug
