Repository cerner/carbon-graphs, pull requests merged in 2019-08, with the labels that each got.

#61 Fix: Non-path based svg icon now translates on-resize (fixes #60)
  build/iconography/buildIcons.js
  dev/examples/helpers.js
  package-lock.json
  package.json
  src/main/js/controls/Bar/helpers/axisInfoRowHelpers.js
  src/main/js/controls/Gantt/helpers/translateHelpers.js
  src/main/js/controls/Line/helpers/helpers.js
  src/main/js/controls/PairedResult/helpers/helpers.js
  src/main/js/controls/PairedResult/helpers/selectionIndicatorHelpers.js
  src/main/js/controls/Timeline/helpers/translateHelpers.js
  src/main/js/core/Shape/Shape.js
  src/main/js/core/Shape/helpers.js
  src/main/js/core/Shape/shapeDefinitions.js
  src/main/js/helpers/dateline.js
  src/test/unit/controls/Bar/Bar-spec.js
  src/test/unit/controls/Gantt/Action-spec.js
  src/test/unit/controls/Gantt/Event-spec.js
  src/test/unit/controls/Gantt/Gantt-spec.js
  src/test/unit/controls/Graph/Graph-spec.js
  src/test/unit/controls/Line/Line-spec.js
  src/test/unit/controls/PairedResult/PairedResult-spec.js
  src/test/unit/controls/Timeline/Timeline-spec.js
  src/test/unit/controls/helpers/commonHelpers.js
  src/test/unit/core/Shape/Shape-spec.js
Labels: bug

#62 Update: Display Data Series In Legend when No Data Exists
  src/main/js/controls/PairedResult/helpers/helpers.js
  src/main/js/core/BaseConfig/helper.js
  src/main/js/helpers/legend.js
  src/main/js/helpers/utils.js
  src/test/unit/controls/Bar/Bar-spec.js
  src/test/unit/controls/Line/Line-spec.js
  src/test/unit/controls/Line/helpers.js
  src/test/unit/controls/PairedResult/PairedResult-spec.js
  src/test/unit/controls/PairedResult/helpers.js
Labels: enhancement, ready to merge

#49 Update: same region show up
  dev/app.js
  dev/examples/controls/bar.js
  dev/examples/controls/combination.js
  dev/examples/controls/line.js
  dev/examples/data.js
  package-lock.json
  src/main/js/controls/Graph/GraphConfig.js
  src/main/js/controls/Line/Line.js
  src/main/js/controls/Line/helpers/helpers.js
  src/main/js/controls/PairedResult/PairedResult.js
  src/main/js/controls/PairedResult/helpers/helpers.js
  src/main/js/helpers/region.js
  src/test/unit/controls/Graph/CombinationGraph-spec.js
  src/test/unit/controls/Line/Line-spec.js
  src/test/unit/controls/Line/helpers.js
  src/test/unit/controls/PairedResult/PairedResult-spec.js
  src/test/unit/controls/PairedResult/helpers.js
Labels: enhancement, ready to merge

#63 New: Added OCS light shapes for Unverified datapoints (fixes #54)
  build/iconography/fileSkeleton.js
  build/iconography/shapesDictionary.js
  dev/app.js
  dev/examples/controls/shapes.js
  dev/examples/data.js
  docs/README.md
  docs/controls/Gantt.md
  docs/controls/Line.md
  docs/controls/PairedResult.md
  docs/controls/Timeline.md
  docs/helpers/Axes.md
  docs/helpers/Dateline.md
  package-lock.json
  package.json
  src/main/js/carbon.js
  src/main/js/core/Shape/shapeDefinitions.js
  src/main/js/helpers/constants.js
  src/test/unit/controls/Carbon/Carbon-spec.js
  src/test/unit/core/Shape/Shape-spec.js
Labels: enhancement

#72 Update: Render demo site with options
  CONTRIBUTORS.md
  dev/app.js
  package-lock.json
  package.json
Labels: chore
