Repository cerner/carbon-graphs, pull requests merged in 2019-12, with the labels that each got.

#107 Update: Constant padding bottom (fixes #81)
  src/main/js/helpers/constants.js
  src/test/unit/controls/Bar/BarPanning-spec.js
  src/test/unit/controls/Gantt/GanttGenerate-spec.js
  src/test/unit/controls/Gantt/GanttLoad-spec.js
  src/test/unit/controls/Gantt/GanttPanning-spec.js
  src/test/unit/controls/Graph/Graph-spec.js
  src/test/unit/controls/Graph/GraphDateline-spec.js
  src/test/unit/controls/Graph/GraphPanning-spec.js
  src/test/unit/controls/Graph/GraphResize-spec.js
  src/test/unit/controls/Line/LinePanning-spec.js
  src/test/unit/controls/Line/LineRegion-spec.js
  src/test/unit/controls/PairedResult/PairedResultPanning-spec.js
  src/test/unit/controls/PairedResult/PairedResultRegion-spec.js
  src/test/unit/helpers/commonHelpers.js
Labels: ready to merge

#120 Docs: Added documentation on X Axis domain padding (fixes #70)
  docs/helpers/Axes.md
  package-lock.json
  package.json
  src/main/js/controls/Gantt/helpers/translateHelpers.js
  src/main/js/controls/Graph/GraphConfig.js
  src/main/js/controls/PairedResult/helpers/helpers.js
  src/main/js/controls/PairedResult/helpers/selectionIndicatorHelpers.js
  src/main/js/controls/Timeline/helpers/translateHelpers.js
Labels: documentation

#118 New: Support Dashed line for Line Graph (fixes #29)
  dev/app.js
  dev/examples/controls/line.js
  dev/examples/data.js
  docs/controls/Line.md
  src/main/js/controls/Line/helpers/helpers.js
  src/test/unit/controls/Line/LineLoad-spec.js
Labels: enhancement

#125 Fix: Y2 axis going out of scope when hasCustomPadding is true.
  src/main/js/controls/Timeline/helpers/creationHelpers.js
  src/main/js/helpers/axis.js
  src/main/js/helpers/constants.js
  src/test/unit/controls/Gantt/GanttGenerate-spec.js
  src/test/unit/controls/Gantt/GanttLoad-spec.js
  src/test/unit/controls/Graph/Graph-spec.js
  src/test/unit/controls/Graph/GraphResize-spec.js
  src/test/unit/controls/Timeline/Timeline-spec.js
  src/test/unit/helpers/commonHelpers.js
Labels: ready to merge

#131 Fix: Opacity for Hashed Activity Bars for Gantt (fixes #113)
  CONTRIBUTORS.md
  dev/examples/controls/gantt.js
  dev/examples/data.js
  package-lock.json
  package.json
  src/main/js/controls/Gantt/helpers/activityHelpers.js
  src/main/js/controls/Gantt/helpers/durationHelpers.js
  src/main/js/helpers/constants.js
  src/test/unit/controls/Gantt/Activity-spec.js
Labels: enhancement

#126 Fix: Padding Top on Timeline changes the width (fixes #117)
  src/main/js/controls/Timeline/helpers/creationHelpers.js
  src/test/unit/controls/Timeline/Timeline-spec.js
Labels: ready to merge

#128 New: Add Scatter Graph
  README.md
  dev/app.js
  dev/examples/controls/criticality.js
  dev/examples/controls/scatter.js
  docs/controls/Scatter.md
  package-lock.json
  src/main/js/controls/Scatter/Scatter.js
  src/main/js/controls/Scatter/ScatterConfig.js
  src/main/js/controls/Scatter/helpers/helpers.js
  src/main/js/controls/Scatter/index.js
  src/main/js/controls/index.js
  src/main/js/helpers/styles.js
  src/test/unit/controls/Carbon/helpers.js
  src/test/unit/controls/Scatter/Scatter-spec.js
  src/test/unit/controls/Scatter/ScatterCriticality-spec.js
  src/test/unit/controls/Scatter/ScatterLoad-spec.js
  src/test/unit/controls/Scatter/ScatterPanning-spec.js
  src/test/unit/controls/Scatter/ScatterUnload-spec.js
  src/test/unit/controls/Scatter/helpers.js
Labels: enhancement
