Repository cerner/carbon-graphs, pull requests merged in 2020-06, with the labels that each got.

#227 Fix: carbon site works in IE (fixes #169)
  package-lock.json
  package.json
Labels: bug

#224 Fix: Fixed Selecting Paired Result Legend Item Affects Multiple Graphs (fixes #212)
  src/main/js/controls/PairedResult/helpers/helpers.js
  src/test/unit/controls/PairedResult/PairedResultLoad-spec.js
Labels: bug-fix, ready to merge

#229 Fix: Red criticality border to not be visible when legend is toggled off and being hovered.
  src/main/less/core.less
Labels: bug-fix, ready to merge

#219 Fix: selection in gantt chart is not surrounding event click(fixes #170)
  package-lock.json
  src/main/js/controls/Gantt/helpers/datapointHelpers.js
  src/main/js/controls/Gantt/helpers/eventHelpers.js
  src/main/js/helpers/constants.js
  src/main/js/helpers/shapeSVG.js
  src/test/unit/controls/Gantt/Event-spec.js
  src/test/unit/controls/Gantt/helpers.js
Labels: bug-fix, ready to merge

#214 Update: color uplift(fixes #193)
  dev/examples/controls/colors.js
  docs/README.md
  src/main/js/helpers/constants.js
  src/test/unit/controls/Bar/BarLoad-spec.js
  src/test/unit/controls/Bar/BarStyles-spec.js
  src/test/unit/controls/Bubble/BubbleLoad-spec.js
  src/test/unit/controls/Gantt/Activity-spec.js
  src/test/unit/controls/Line/LineLoad-spec.js
  src/test/unit/controls/PairedResult/PairedResultLoad-spec.js
  src/test/unit/controls/Scatter/ScatterLoad-spec.js
  src/test/unit/controls/Timeline/TimelineLoad-spec.js
Labels: :star: Accessibility Reviewed, :star: UX Reviewed, enhancement, ready to merge

#216 Fix: fixed Y & Y2 ticks misalignment (fixes #209)
  docs/core/Graph.md
  docs/helpers/Ticks.md
  package-lock.json
  src/main/js/helpers/axis.js
  src/main/js/helpers/constants.js
  src/test/unit/controls/Graph/GraphAxes-spec.js
Labels: :star: UX Reviewed, bug-fix

#213 Fix graph padding (Issue-207)
  dev/app.js
  dev/app.less
  dev/examples/controls/bar.js
  dev/examples/controls/bubble.js
  dev/examples/controls/gantt.js
  dev/examples/controls/line.js
  dev/examples/controls/pairedResult.js
  dev/examples/controls/pie.js
  dev/examples/controls/scatter.js
  dev/examples/controls/timeline.js
  dev/examples/helpers.js
  docs/controls/Gantt.md
  docs/controls/Padding.md
  docs/controls/Pie.md
  docs/controls/Timeline.md
  docs/core/Graph.md
  src/main/js/controls/Bar/helpers/creationHelpers.js
  src/main/js/controls/Bubble/helpers/helpers.js
  src/main/js/controls/Gantt/Gantt.js
  src/main/js/controls/Gantt/GanttConfig.js
  src/main/js/controls/Gantt/helpers/actionHelpers.js
  src/main/js/controls/Graph/Graph.js
  src/main/js/controls/Graph/GraphConfig.js
  src/main/js/controls/Line/helpers/helpers.js
  src/main/js/controls/PairedResult/helpers/helpers.js
  src/main/js/controls/Pie/Pie.js
  src/main/js/controls/Pie/PieConfig.js
  src/main/js/controls/Pie/PieContent.js
  src/main/js/controls/Pie/helpers/creationHelpers.js
  src/main/js/controls/Scatter/helpers/helpers.js
  src/main/js/controls/Timeline/Timeline.js
  src/main/js/controls/Timeline/TimelineConfig.js
  src/main/js/controls/Timeline/helpers/creationHelpers.js
  src/main/js/helpers/constants.js
  src/main/js/helpers/legend.js
  src/main/less/controls/Pie.less
  src/main/less/core.less
  src/test/unit/controls/Gantt/GanttEventline-spec.js
  src/test/unit/controls/Gantt/GanttGenerate-spec.js
  src/test/unit/controls/Gantt/GanttLoad-spec.js
  src/test/unit/controls/Graph/Graph-spec.js
  src/test/unit/controls/Graph/GraphResize-spec.js
  src/test/unit/helpers/commonHelpers.js
Labels: :star: UX Reviewed, UX Review Required, enhancement

#247 Chore: Update the husky hooks and .releaserc tags (fixes #237)
  .releaserc
  docs/contributing/README.md
  package.json
Labels: chore
