Repository cerner/carbon-graphs, pull requests merged in 2020-01, with the labels that each got.

#137 New: Added Container padding/margin (fixes #121)
  dev/app.js
  dev/app.less
  dev/examples/controls/gantt.js
  dev/examples/controls/line.js
  dev/examples/controls/timeline.js
  dev/examples/helpers.js
  docs/assets/graph-container.png
  docs/assets/graph-content.png
  docs/controls/Padding.md
  src/main/js/controls/Gantt/Gantt.js
  src/main/js/controls/Graph/Graph.js
  src/main/js/controls/Timeline/Timeline.js
  src/main/js/helpers/paddingUtils.js
  src/test/unit/controls/Gantt/Gantt-spec.js
  src/test/unit/controls/Graph/Graph-spec.js
  src/test/unit/controls/Timeline/Timeline-spec.js
Labels: enhancement

#139 Fix: Added getPadding to timeline to fix padding issue (fixes #136)
  src/main/js/controls/Timeline/TimelineConfig.js
  src/test/unit/controls/Timeline/Timeline-spec.js
Labels: enhancement

#149 Upgrade: Chore update dev dependencies
  .eslintrc.json
  package-lock.json
  package.json
Labels: chore

#135 New: Eventline
  dev/app.js
  dev/examples/controls/bar.js
  dev/examples/controls/gantt.js
  dev/examples/controls/line.js
  dev/examples/controls/pairedResult.js
  dev/examples/controls/scatter.js
  docs/README.md
  docs/helpers/Eventline.md
  src/main/js/controls/Gantt/Gantt.js
  src/main/js/controls/Gantt/GanttConfig.js
  src/main/js/controls/Gantt/helpers/translateHelpers.js
  src/main/js/controls/Graph/Graph.js
  src/main/js/controls/Graph/GraphConfig.js
  src/main/js/controls/Graph/helpers/helpers.js
  src/main/js/helpers/errors.js
  src/main/js/helpers/eventline.js
  src/main/js/helpers/styles.js
  src/main/less/core.less
  src/test/unit/controls/Gantt/Gantt-spec.js
  src/test/unit/controls/Gantt/GanttEventline-spec.js
  src/test/unit/controls/Gantt/helpers.js
  src/test/unit/controls/Graph/Graph-spec.js
  src/test/unit/controls/Graph/GraphEventline-spec.js
  src/test/unit/controls/Graph/helpers.js
Labels: enhancement

#152 Update: Add missing unit tests for Scatter Graph (Fixes #151)
  src/test/unit/controls/Carbon/Carbon-spec.js
  src/test/unit/controls/Scatter/ScatterRegion-spec.js
Labels: chore

#140 Fix: Graph API now preserves order of content loaded (fixes #13)
  src/main/js/controls/Bar/helpers/legendHelpers.js
  src/main/js/controls/Line/helpers/helpers.js
  src/main/js/controls/PairedResult/helpers/helpers.js
  src/main/js/controls/Scatter/helpers/helpers.js
  src/main/js/controls/Timeline/helpers/creationHelpers.js
  src/main/js/helpers/legend.js
  src/test/unit/controls/Bar/BarLoad-spec.js
  src/test/unit/controls/Graph/CombinationGraph-spec.js
  src/test/unit/controls/Line/LineLoad-spec.js
  src/test/unit/controls/PairedResult/PairedResultLoad-spec.js
  src/test/unit/controls/Scatter/ScatterLoad-spec.js
  src/test/unit/controls/Timeline/TimelineLoad-spec.js
Labels: bug
