Repository cerner/carbon-graphs, pull requests merged in 2020-09, with the labels that each got.

#292 Update: Reduce gap in betweeen y-axis and y-axis label(fixes #30)
  dev/examples/controls/line.js
  src/main/js/helpers/axis.js
  src/test/unit/controls/Graph/GraphGenerate-spec.js
Labels: :star: ux reviewed, enhancement, enhancement-fix

#290 Fix: Label Should Update With Reflow(fixes #277)
  dev/examples/controls/line.js
  src/main/js/controls/Bar/Bar.js
  src/main/js/controls/Bubble/Bubble.js
  src/main/js/controls/Graph/Graph.js
  src/main/js/controls/Line/Line.js
  src/main/js/controls/PairedResult/PairedResult.js
  src/main/js/controls/Scatter/Scatter.js
  src/test/unit/controls/Bar/BarPanning-spec.js
  src/test/unit/controls/Bar/helpers.js
  src/test/unit/controls/Bubble/BubblePanning-spec.js
  src/test/unit/controls/Bubble/helpers.js
  src/test/unit/controls/Line/LinePanning-spec.js
  src/test/unit/controls/Line/helpers.js
  src/test/unit/controls/PairedResult/PairedResultPanning-spec.js
  src/test/unit/controls/PairedResult/helpers.js
  src/test/unit/controls/Scatter/ScatterPanning-spec.js
  src/test/unit/controls/Scatter/helpers.js
Labels: :star: ux reviewed, bug-fix

#296 Chore: added .prettierignore and executed linter
  .prettierignore
  src/main/js/helpers/legend.js
Labels: chore

#293 Fix: Center Gantt chunks(fixes #31)
  src/main/js/core/Shape/shapeDefinitions.js
Labels: :star: ux reviewed, bug-fix

#294 Docs: Updated issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: chore

#299 Fix: Region doesn't show face up (fixes #284 )
  src/main/js/controls/Bubble/helpers/helpers.js
  src/main/js/controls/Line/Line.js
  src/main/js/controls/Line/helpers/helpers.js
  src/main/js/controls/PairedResult/PairedResult.js
  src/main/js/controls/PairedResult/helpers/helpers.js
  src/main/js/controls/Scatter/helpers/helpers.js
  src/main/js/helpers/region.js
  src/test/unit/controls/Line/LineRegion-spec.js
  src/test/unit/controls/PairedResult/PairedResultRegion-spec.js
Labels: :star: ux reviewed, bug-fix

#300 Fix: stacked bar legend toggle(fixes #283)
  dev/examples/controls/bar.js
  src/main/js/controls/Bar/helpers/legendHelpers.js
  src/test/unit/controls/Bar/BarRegions-spec.js
  src/test/unit/controls/Bar/GroupedBar-spec.js
  src/test/unit/controls/Bar/StackedBar-spec.js
Labels: :star: ux reviewed, bug-fix

#301 Remove symbols with data set is removed from legend(Fixes #286).
  dev/examples/controls/pairedResult.js
  src/main/js/controls/Bar/Bar.js
  src/main/js/controls/Graph/Graph.js
  src/main/js/controls/Line/Line.js
  src/main/js/controls/PairedResult/PairedResult.js
  src/main/js/controls/Scatter/Scatter.js
  src/test/unit/controls/Bar/BarPanning-spec.js
  src/test/unit/controls/Line/LinePanning-spec.js
  src/test/unit/controls/PairedResult/PairedResultPanning-spec.js
  src/test/unit/controls/Scatter/ScatterPanning-spec.js
Labels: :star: ux reviewed, bug-fix

#303 Updating .gitignore to ignore package-lock.json
  .gitignore
Labels: build, chore
