Repository cerner/carbon-graphs, pull requests merged in 2020-04, with the labels that each got.

#200 Upgrade: Greenkeeper/eslint plugin jsdoc 24.0.0
  package-lock.json
  package.json
Labels: greenkeeper

#197 New: Paired Result with Symbol and Line in Legend
  dev/app.js
  dev/examples/controls/pairedResult.js
  dev/examples/data.js
  src/main/js/controls/PairedResult/helpers/helpers.js
  src/test/unit/controls/PairedResult/PairedResultLoad-spec.js
Labels: enhancement, ⭐️ UX Reviewed

#183 Fix: Added border for legend when toggled off state
  src/main/less/core.less
Labels: bug-fix, ⭐️ UX Reviewed

#186 Fixed diamond shapes datapoint to align with the time they occur in
  src/main/js/core/Shape/shapeDefinitions.js
Labels: bug-fix, ⭐️ UX Reviewed
