Repository cerner/carbon-graphs, pull requests merged in 2020-02, with the labels that each got.

#145 New: Bubble graph
  README.md
  dev/app.js
  dev/examples/controls/bubble.js
  dev/examples/popup.js
  docs/controls/Bubble.md
  package-lock.json
  src/main/js/controls/Bubble/Bubble.js
  src/main/js/controls/Bubble/BubbleConfig.js
  src/main/js/controls/Bubble/helpers/colorGradient.js
  src/main/js/controls/Bubble/helpers/helpers.js
  src/main/js/controls/Bubble/index.js
  src/main/js/controls/index.js
  src/main/js/helpers/constants.js
  src/main/js/helpers/styles.js
  src/test/unit/controls/Bubble/Bubble-spec.js
  src/test/unit/controls/Bubble/BubbleLoad-spec.js
  src/test/unit/controls/Bubble/BubblePanning-spec.js
  src/test/unit/controls/Bubble/BubbleRegion-spec.js
  src/test/unit/controls/Bubble/BubbleUnload-spec.js
  src/test/unit/controls/Bubble/helpers.js
  src/test/unit/controls/Carbon/Carbon-spec.js
  src/test/unit/controls/Carbon/helpers.js
Labels: enhancement, ready to merge, ⭐️ UX Reviewed

#164 Fix: Fixed graphs to not render data points where y value is null.
  src/main/js/controls/Gantt/helpers/actionHelpers.js
  src/main/js/controls/Line/helpers/helpers.js
  src/main/js/controls/Scatter/helpers/helpers.js
  src/main/js/controls/Timeline/helpers/creationHelpers.js
  src/test/unit/controls/Line/LineLoad-spec.js
  src/test/unit/controls/Scatter/ScatterLoad-spec.js
Labels: bug

#166 New: Legend Item Symbol Dashed Line
  dev/app.js
  dev/examples/controls/line.js
  dev/examples/data.js
  docs/controls/Line.md
  src/main/js/controls/Line/helpers/helpers.js
  src/main/js/core/BaseConfig/helper.js
  src/main/js/helpers/constants.js
  src/main/js/helpers/legend.js
  src/main/js/helpers/styles.js
  src/main/less/core.less
  src/test/unit/controls/Bar/BarLoad-spec.js
  src/test/unit/controls/Bubble/BubbleLoad-spec.js
  src/test/unit/controls/Line/LineLoad-spec.js
  src/test/unit/controls/PairedResult/PairedResultLoad-spec.js
  src/test/unit/controls/Scatter/ScatterLoad-spec.js
  src/test/unit/controls/Timeline/TimelineLoad-spec.js
Labels: enhancement
