Repository cerner/carbon-graphs, pull requests merged in 2020-07, with the labels that each got.

#249 Fix: updated Y-axes tick logic (fixes #235)
  docs/core/Graph.md
  docs/helpers/Ticks.md
  package-lock.json
  src/main/js/helpers/axis.js
  src/test/unit/controls/Graph/GraphAxes-spec.js
Labels: :star: UX Reviewed, bug-fix

#248 New: Suppress Tick Values Trailing Zeros (fixes #234)
  dev/app.js
  dev/examples/controls/line.js
  dev/examples/data.js
  docs/README.md
  docs/core/Graph.md
  docs/helpers/Axes.md
  docs/helpers/Ticks.md
  package-lock.json
  package.json
  src/main/js/controls/Graph/GraphConfig.js
  src/main/js/helpers/axis.js
  src/test/unit/controls/Graph/GraphAxes-spec.js
Labels: :star: UX Reviewed, enhancement

#251 New: Suppressing Legend Items
  dev/app.js
  dev/examples/controls/line.js
  dev/examples/data.js
  docs/controls/Bar.md
  docs/controls/Bubble.md
  docs/controls/Line.md
  docs/controls/PairedResult.md
  docs/controls/Scatter.md
  src/main/js/helpers/legend.js
  src/test/unit/controls/Line/LineLoad-spec.js
Labels: :star: UX Reviewed, enhancement

#242 Fix: graph Axis Label Truncation(fixes #208)
  dev/app.js
  dev/examples/controls/gantt.js
  dev/examples/controls/line.js
  dev/examples/data.js
  dev/examples/popup.js
  docs/controls/Bar.md
  docs/controls/Bubble.md
  docs/controls/PairedResult.md
  docs/controls/Scatter.md
  docs/helpers/Axes.md
  src/main/js/controls/Gantt/Track.js
  src/main/js/controls/Graph/helpers/helpers.js
  src/main/js/helpers/axis.js
  src/main/js/helpers/label.js
  src/main/js/helpers/legend.js
  src/test/unit/controls/Gantt/Track-spec.js
  src/test/unit/controls/Graph/GraphAxes-spec.js
  src/test/unit/controls/Line/LineLoad-spec.js
Labels: :star: UX Reviewed, bug-fix, ready to merge

#263 Fix: Gantt chart unloading issue(fixes #245, #256)
  src/main/js/controls/Gantt/Track.js
  src/test/unit/controls/Gantt/Action-spec.js
  src/test/unit/controls/Gantt/Track-spec.js
Labels: bug-fix

#138 New: Added function reflow for panning in graphs.
  .eslintrc.json
  dev/app.js
  dev/examples/controls/bar.js
  dev/examples/controls/bubble.js
  dev/examples/controls/gantt.js
  dev/examples/controls/line.js
  dev/examples/controls/pairedResult.js
  dev/examples/controls/scatter.js
  dev/examples/controls/timeline.js
  dev/examples/data.js
  dev/examples/panHelpers.js
  docs/controls/Panning.md
  package-lock.json
  package.json
  src/main/js/controls/Bar/Bar.js
  src/main/js/controls/Bar/helpers/creationHelpers.js
  src/main/js/controls/Bubble/Bubble.js
  src/main/js/controls/Bubble/helpers/helpers.js
  src/main/js/controls/Gantt/Gantt.js
  src/main/js/controls/Gantt/Track.js
  src/main/js/controls/Gantt/helpers/actionHelpers.js
  src/main/js/controls/Gantt/helpers/activityHelpers.js
  src/main/js/controls/Gantt/helpers/datapointHelpers.js
  src/main/js/controls/Gantt/helpers/eventHelpers.js
  src/main/js/controls/Gantt/helpers/taskHelpers.js
  src/main/js/controls/Gantt/helpers/translateHelpers.js
  src/main/js/controls/Graph/Graph.js
  src/main/js/controls/Line/Line.js
  src/main/js/controls/Line/helpers/helpers.js
  src/main/js/controls/PairedResult/PairedResult.js
  src/main/js/controls/PairedResult/helpers/helpers.js
  src/main/js/controls/Scatter/Scatter.js
  src/main/js/controls/Scatter/helpers/helpers.js
  src/main/js/controls/Timeline/Timeline.js
  src/main/js/controls/Timeline/TimelineContent.js
  src/main/js/controls/Timeline/helpers/creationHelpers.js
  src/main/js/controls/Timeline/helpers/translateHelpers.js
  src/main/js/helpers/axis.js
  src/test/unit/controls/Bar/BarPanning-spec.js
  src/test/unit/controls/Bubble/BubblePanning-spec.js
  src/test/unit/controls/Bubble/helpers.js
  src/test/unit/controls/Gantt/GanttPanning-spec.js
  src/test/unit/controls/Gantt/helpers.js
  src/test/unit/controls/Line/LinePanning-spec.js
  src/test/unit/controls/Line/helpers.js
  src/test/unit/controls/PairedResult/PairedResultPanning-spec.js
  src/test/unit/controls/PairedResult/helpers.js
  src/test/unit/controls/Scatter/ScatterPanning-spec.js
  src/test/unit/controls/Scatter/helpers.js
  src/test/unit/controls/Timeline/TimelinePanning-spec.js
Labels: :star: UX Reviewed, enhancement, ready to merge

#269 Update: Adding Coverage summary to Travis build
  build/karma/karma.config.js
Labels: chore, ready to merge

#272 Fix: updated styling to fix popup issue(fixes #271, #6)
  dev/examples/data.js
  src/main/js/controls/Gantt/Gantt.js
  src/main/js/controls/Graph/Graph.js
  src/main/js/helpers/label.js
  src/main/js/helpers/styles.js
  src/main/less/core.less
  src/test/unit/controls/Gantt/Track-spec.js
  src/test/unit/controls/Graph/GraphAxes-spec.js
Labels: bug-fix

#258 New: Enhance Reference Range (Fixes #267)
  dev/app.js
  dev/examples/controls/line.js
  dev/examples/controls/pairedResult.js
  dev/examples/controls/spline.js
  dev/examples/data.js
  docs/controls/Line.md
  docs/controls/PairedResult.md
  src/main/js/controls/Line/Line.js
  src/main/js/controls/Line/helpers/helpers.js
  src/main/js/controls/PairedResult/PairedResult.js
  src/main/js/controls/PairedResult/helpers/helpers.js
  src/main/js/helpers/region.js
  src/main/js/helpers/styles.js
  src/main/less/core.less
  src/test/unit/controls/Line/LineRegion-spec.js
  src/test/unit/controls/PairedResult/PairedResultRegion-spec.js
Labels: :star: UX Reviewed, enhancement

#282 Fix: Fixes Graph padding issue when show label is set (fixes #278)
  src/main/js/controls/Graph/Graph.js
  src/test/unit/controls/Graph/GraphResize-spec.js
  src/test/unit/controls/Graph/helpers.js
Labels: bug-fix
